# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  run:
    cmds:
      - go run .
  llvm1:
    cmds:
      - go run ./llvm/llvmSample1
      - lli ./output.ll
  llvm:
    cmds:
      - go run ./llvm/main
      - lli ./output.ll
